// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmAbKhztB5qEz0qwvh4ACzA_r9HSEH-a0',
    appId: '1:463623558358:web:99792fe8fda895d34f2577',
    messagingSenderId: '463623558358',
    projectId: 'kbalay-bf430',
    authDomain: 'kbalay-bf430.firebaseapp.com',
    storageBucket: 'kbalay-bf430.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRdbcza6q655Nq6Fv-fQnZP346RXEe_u0',
    appId: '1:463623558358:android:684763a992307b514f2577',
    messagingSenderId: '463623558358',
    projectId: 'kbalay-bf430',
    storageBucket: 'kbalay-bf430.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQMgWN0GiuJnIxWkJ0Nr8YQ2JxK4jQcOM',
    appId: '1:463623558358:ios:d8fe4dbcdc5acde44f2577',
    messagingSenderId: '463623558358',
    projectId: 'kbalay-bf430',
    storageBucket: 'kbalay-bf430.firebasestorage.app',
    iosBundleId: 'com.example.flutterHoa',
  );

}